.\" Hey, EMACS: -*- nroff -*-
.\" Copyright (C) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
.\" 2008, 2009 Free Software Foundation, Inc.
.\"
.\" This document is dual-licensed.  You may distribute and/or modify it
.\" under the terms of either of the following licenses:
.\"
.\" * The GNU General Public License, as published by the Free Software
.\"   Foundation, version 3 or (at your option) any later version.  You
.\"   should have received a copy of the GNU General Public License
.\"   along with this program.  If not, see
.\"   <http://www.gnu.org/licenses/>.
.\"
.\" * The GNU Free Documentation License, as published by the Free
.\"   Software Foundation, version 1.2 or (at your option) any later
.\"   version, with no Invariant Sections, no Front-Cover Texts, and no
.\"   Back-Cover Texts.  You should have received a copy of the GNU Free
.\"   Documentation License along with this program.  If not, see
.\"   <http://www.gnu.org/licenses/>.
.\"
.\" $Id: nano.1 4502 2010-04-14 21:55:39Z astyanax $
.TH PINOT 1 "version 0.0.8" "July 2, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"

.SH NAME
pinot \- Enhanced version of the GNU nano editor

.SH SYNOPSIS
.B pinot
.RI [ options "] [[+" line , column "]\ " file "]..."

.SH DESCRIPTION
This manual page briefly documents the \fBpinot\fP command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
\fBpinot\fP is a small, free and friendly editor which aims to replace
GNU nano for developers. It removes some of nano's general text-editing
features by default (particularly the spell checker and text justification)
while adding some developer-friendly features like PCRE regular expressions.

.SH EDITING
Entering text and moving around in a file is straightforward: typing the
letters and using the normal cursor movement keys.  Commands are entered
by using the Control (^) and the Alt or Meta (M-) keys.
Typing \fB^K\fR deletes the current line and puts it in the cutbuffer.
Consecutive \fB^K\fRs will put all deleted lines together in the cutbuffer.
Any cursor movement or executing any other command will cause the next
\fB^K\fR to overwrite the cutbuffer.  A \fB^U\fR will paste the current
contents of the cutbuffer at the current cursor position.
.PP
When a more precise piece of text needs to be cut or copied, one can mark
its start with \fB^6\fR, move the cursor to its end (the marked text will be
highlighted), and then use \fB^K\fR to cut it, or \fBM-6\fR to copy it to the
cutbuffer. One can also save the marked text to a file with \fB^O\fR, or
spell check it with \fB^T\fR.
.PP
The two lines at the bottom of the screen show the most important commands;
the built-in help (\fB^G\fR) lists all the available ones.
The default key bindings can be changed via the .pinotrc file -- see
.BR pinotrc (5).

.SH OPTIONS
.TP
.B +\fIline\fP,\fIcolumn\fP
Places cursor at line number \fIline\fP and column number \fIcolumn\fP
(at least one of which must be specified) on startup, instead of the
default of line 1, column 1.
.TP
.B \-?
Same as \fB-h (\-\-help)\fP.
.TP
.BR \-A ", " \-\-smarthome
Make the Home key smarter.  When Home is pressed anywhere but at the
very beginning of non-whitespace characters on a line, the cursor will
jump to that beginning (either forwards or backwards).  If the cursor is
already at that position, it will jump to the true beginning of the
line.
.TP
.BR \-B ", " \-\-backup
When saving a file, back up the previous version of it, using the current
filename suffixed with a ~.
.TP
.BR \-C\ \fIdirectory\fR ", " \-\-backupdir= \fIdirectory
Make and keep not just one backup file, but make and keep a uniquely
numbered one every time a file is saved -- when backups are enabled.
The uniquely numbered files are stored in the specified \fIdirectory\fR.
.TP
.BR \-D ", " \-\-boldtext
Use bold text instead of reverse video text.
.TP
.BR \-E ", " \-\-tabstospaces
Convert typed tabs to spaces.
.TP
.BR \-F ", " \-\-multibuffer
Enable multiple file buffers, if available.
.TP
.BR \-G ", " \-\-locking
Enable vim-style file locking when editing files.
.TP
.BR \-H ", " \-\-historylog
Log search and replace strings to \fI~/.pinot/search_history\fP, so they can be
retrieved in later sessions, if \fIpinotrc\fP support is available.
.TP
.BR \-I ", " \-\-ignorercfiles
Don't look at \fISYSCONFDIR/pinorrc\fP or \fI~/.pinotrc\fP, if
\fIpinotrc\fP support is available.
.TP
.BR \-K ", " \-\-rebindkeypad
Interpret the numeric keypad keys so that they all work properly.  You
should only need to use this option if they don't, as mouse support
won't work properly with this option enabled.
.TP
.BR \-L ", " \-\-nonewlines
Don't add newlines to the ends of files.
.TP
.BR \-N ", " \-\-noconvert
Disable automatic conversion of files from DOS/Mac format.
.TP
.BR \-O ", " \-\-morespace
Use the blank line below the titlebar as extra editing space.
.TP
.BR \-P ", " \-\-poslog
Log & read location of cursor position.
.TP
.BR \-S ", " \-\-smooth
Enable smooth scrolling.  Text will scroll line-by-line, instead of the
usual chunk-by-chunk behavior.
.TP
.BR \-T\ \fInumber\fR ", " \-\-tabsize= \fInumber
Set the size (width) of a tab to \fInumber\fP columns.  The value of
\fInumber\fP must be greater than 0.  The default value is 8.
.TP
.BR \-U ", " \-\-quickblank
Do quick statusbar blanking.  Statusbar messages will disappear after 1
keystroke instead of 25.  Note that \fB-c\fP overrides this.
.TP
.BR \-V ", " \-\-version
Show the current version number and exit.
.TP
.BR \-W ", " \-\-wordbounds
Detect word boundaries more accurately by treating punctuation
characters as part of a word.
.TP
.BR \-Y\ \fIname\fR ", " \-\-syntax= \fIname
Specify a specific syntax highlighting from the \fIpinotrc\fP to use, if
available.
.TP
.BR \-c ", " \-\-const
Constantly show the cursor position.  Note that this overrides \fB-U\fP.
.TP
.BR \-h ", " \-\-help
Show a summary of command line options and exit.
.TP
.BR \-i ", " \-\-autoindent
Indent new lines to the previous line's indentation.  Useful when
editing source code.
.TP
.BR \-k ", " \-\-cut
Enable cut from cursor to end of line.
.TP
.BR \-l ", " \-\-nofollow
If the file being edited is a symbolic link, replace the link with
a new file instead of following it.  Good for editing files in
\fI/tmp\fP, perhaps?
.TP
.BR \-p ", " \-\-preserve
Preserve the XON and XOFF sequences (^Q and ^S) so they will be caught
by the terminal.
.TP
.BR \-q ", " \-\-quiet
Do not report errors in the \fIpinotrc\fP file and ask them to be
acknowledged by pressing Enter at startup.
.TP
.BR \-r\ \fInumber\fR ", " \-\-fill= \fInumber
Wrap lines at column \fInumber\fP.  If this value is 0 or less, wrapping
will occur at the width of the screen less \fInumber\fP columns, allowing
the wrap point to vary along with the width of the screen if the screen
is resized.  The default value is \-8.
.TP
.BR \-s\ \fIprogram\fR ", " \-\-speller= \fIprogram
Use this alternative spell checker command.
.TP
.BR \-t ", " \-\-tempfile
Always save a changed buffer without prompting.  Same as Pico's \fB-t\fP
option.
.TP
.BR \-v ", " \-\-view
View file (read only) mode.
.TP
.BR \-w ", " \-\-nowrap
Disable wrapping of long lines.
.TP
.BR \-x ", " \-\-nohelp
Disable help screen at bottom of editor.
.TP
.BR \-z ", " \-\-suspend
Enable suspend ability.
.TP
.BR \-$ ", " \-\-softwrap
Enable 'soft wrapping'.  \fBpinot\fP will attempt to display the entire
contents of a line, even if it is longer than the screen width.  Since
\&'$' normally refers to a variable in the Unix shell, you should specify
this option last when using other options (e.g.\& 'pinot \-wS$') or pass it
separately (e.g.\& 'pinot \-wS \-$').

.SH INITIALIZATION FILE
\fBpinot\fP will read initialization files in the following order:
\fISYSCONFDIR/pinotrc\fP, then \fI~/.pinotrc\fP.  Please see
\fBpinotrc(5)\fP and the example file \fBpinotrc.sample\fP, both of which
should be provided with \fBpinot\fP.

.SH NOTES
If no alternative spell checker command is specified on the command
line or in one of the \fIpinotrc\fP files, \fBpinot\fP will check the
\fBSPELL\fP environment variable for one.

In some cases \fBpinot\fP will try to dump the buffer into an emergency
file.  This will happen mainly if \fBpinot\fP receives a SIGHUP or
SIGTERM or runs out of memory.  It will write the buffer into a file
named \fIpinot.save\fP if the buffer didn't have a name already, or will
add a ".save" suffix to the current filename.  If an emergency file with
that name already exists in the current directory, it will add ".save"
plus a number (e.g.\& ".save.1") to the current filename in order to make
it unique.  In multibuffer mode, \fBpinot\fP will write all the open
buffers to their respective emergency files.

.SH BUGS
Please report any bugs at \fBhttps://github.com/pgengler/pinot/issues\fP.

.SH HOMEPAGE
https://github.com/pgengler/pinot

.SH SEE ALSO
.PD 0
.TP
\fBpinotrc\fP(5)
.PP
\fI/usr/share/doc/pinot/\fP (or equivalent on your system)

.SH AUTHOR
Chris Allegretta <chrisa@asty.org>, et al (see \fIAUTHORS\fP and
\fITHANKS\fP for details).  This manual page was originally written by
Jordi Mallach <jordi@gnu.org>, for the Debian system (but may be used by
others).
