# unattributed syntax highlighting example from wiki.linuxhelp.net/

syntax "makefile" "Makefile[^/]*$"
color red "[:=]"
color magenta "\b(if|ifeq|else|endif)\b"
color blue "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
color green "#.*$"
